chore: add commitizen to ease semver commits
contentful/contentful-migration pull request #568
Opened 2020-11-23 12:11 UTC by anho

## Summary

Ease generation of correct commit msgs.

2020-11-23 14:01 UTC, ruderngespra requested changes
This seems like a nice tool, but could you explain why we have to add updated nock files and api key secrets and space ids?  Wouldn't that be a problem for a public repository?

2020-11-23 14:07 UTC, anho commented
@ruderngespra ouch, glad someone caught that. That was me accidentally pushing playground stuff. It's gone now.

2020-11-23 17:25 UTC, suevalov approved these changes

2020-11-24 08:15 UTC, ruderngespra approved these changes
:+1: :)

2020-11-24 09:01 UTC, merged